### PR TITLE
provide a standards-required manual page

### PR DESCRIPTION
**Pull request by exaexa**
A very-recommended feature for debianization.

### CODE REVIEW

**Comment by i-rinat** [comment]
Looks good. Thanks!

**Comment by exaexa** [comment]
Thanks a lot! Anyway, just a info about debianization -- now it's in NEW queue here:

https://ftp-master.debian.org/new/apulse_0.1.10+git20171103-1.html

**Comment by i-rinat** [comment]
> https://ftp-master.debian.org/new/apulse_0.1.10+git20171103-1.html

Looks like there could be issues with multiarch — files in /usr/lib/apulse/ will conflict.

A while ago, I tried to create a package. Previously, `checkinstall` worked just fine, but only for a single architecture. Installing both 32-bit and 64-bit versions at the same time was not possible. I ended up with a set of scripts like this: https://github.com/i-rinat/apulse-debpkg

**Comment by exaexa** [comment]
Good point, thanks. I guess I'll be able to find a good&accepted solution in some other debian package.

**Pull request merged**
